using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Engines;
using Data;
using Microsoft.EntityFrameworkCore;
using ORM0Entities;
using ORM0Entities.autogenerated;

namespace F0Inserttests;

[SimpleJob(RunStrategy.Throughput)]
[JsonExporter(fileNameSuffix:"",indentJson:true)]
[RPlotExporter]
[CsvMeasurementsExporter]
[IterationCount(20)]
[WarmupCount(20)]


public class F0InsertPerforamnceNToM : F0GlobalConfig.F0GlobalConfig
{
    public IEnumerable<int> valuesForNumberOfStatements() => NumberOfBills;
    
    [ParamsSource(nameof(valuesForNumberOfStatements))] 
    public int numberOfStatements;

    [GlobalSetup]
    public void GlobalSetup()
    {
        DefineDatabaseModelUsingScript(FilePath);
    }
   
    private List<Article> articleList = new List<Article>();
    private int cache = -1;
    [IterationSetup]
    public void SetUp()
    {
        if (cache != numberOfStatements)
        {
            SetUpGenericF0();
            listInsertBills = NBuilderHelper.GetBillsAndArticles(numberOfStatements, NumberOfArticles, MinArticlesToTryAdd, MaxArticlesToTryAdd,articleList);
            cache = numberOfStatements;
        }
        else
        {
            var tempList = listInsertBills;
            SetUpGenericF0();
            listInsertBills = tempList;
        }
    }

    [IterationCleanup]
    public void CleanUp()
    {
      CleanBillsArticles();
    }

    [Benchmark]
    public void InsertData()
    {
        foreach (Bill item in listInsertBills)
        {
            foreach (Article item2 in item.FkArticles)
            {
                item2.FkBills = new List<Bill>();
            }
        }
        for (var i = 0; i < listInsertBills.Count; i++)
        {
            context.Bills.Add(listInsertBills[i]);
            context.SaveChanges();
        }
    }
}