using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Engines;
using Data;
using ORM0Entities;
using ORM0Entities.autogenerated;

namespace F0SelectTests;

[SimpleJob(RunStrategy.Throughput)]
[JsonExporter(fileNameSuffix:"",indentJson:true)]
[RPlotExporter]
[CsvMeasurementsExporter]
[IterationCount(20)]
[WarmupCount(20)]

public class F0SelectPerformanceNoRelation : F0GlobalConfig.F0GlobalConfig
{
    public IEnumerable<int> valuesForNumberOfStatements() => NumberOfCustomers;
    
    [ParamsSource(nameof(valuesForNumberOfStatements))] 
    public int numberOfStatements;

    [GlobalSetup]
    public void GlobalSetup()
    {
        DefineDatabaseModelUsingScript(FilePath);
    }
   
    private int cache = -1;
    [IterationSetup]
    public void SetUp()
    {
        if (cache != numberOfStatements)
        {
            SetUpGenericF0();
            listInsertCustomers = NBuilderHelper.GetListOfCustomerInformation1To1(numberOfStatements);
            cache = numberOfStatements;
        }
        else
        {
            var tempList = listInsertCustomers;
            SetUpGenericF0();
            listInsertCustomers = tempList;
        }
        
        
        for (var i = 0; i < listInsertCustomers.Count; i++)
        {
            context.Customers.Add(listInsertCustomers[i]);
            context.SaveChanges();
        }
        ResetCache();
    }
    [IterationCleanup]
    public void CleanUp()
    {
        CleanCustomers();
    }

    [Benchmark]
    public void SelectData()
    {
        for (int i = 0; i < listInsertCustomers.Count; i++)
        {
            listGetCustomers.Add(context.Customers.First(c => c.Customerid == listInsertCustomers[i].Customerid));
        }
    }
}
