using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Engines;
using ORM0Entities;
using ORM0Entities.autogenerated;

namespace F0UpdateTest;

[SimpleJob(RunStrategy.Throughput)]
[JsonExporter(fileNameSuffix:"",indentJson:true)]
[RPlotExporter]
[CsvMeasurementsExporter]
[IterationCount(20)]
[WarmupCount(20)]

public class F0UpdatePerformanceNoRelation : F0GlobalConfig.F0GlobalConfig
{
    public IEnumerable<int> valuesForNumberOfStatements() => NumberOfCustomers;
    
    [ParamsSource(nameof(valuesForNumberOfStatements))] 
    public int numberOfStatements;

    [GlobalSetup]
    public void GlobalSetup()
    {
        DefineDatabaseModelUsingScript(FilePath);
    }
   
    private int cache = -1;
    [IterationSetup]
    public void SetUp()
    {
        if (cache != numberOfStatements)
        {
            SetUpGenericF0();
            listInsertCustomers = NBuilderHelper.GetListOfCustomerInformation1To1(numberOfStatements);
            cache = numberOfStatements;
        }
        else
        {
            var tempList = listInsertCustomers;
            SetUpGenericF0();
            listInsertCustomers = tempList;
            for (int i = 0; i < listInsertCustomers.Count; i++)
            {
                Customer temp = listInsertCustomers[i];
                temp.Email = "bbbbbbbb";
                temp.Customerlikescolorgreen = !temp.Customerlikescolorgreen;
                temp.Lastname = "bbbbbbbb";
            }
        }
        
        
        for (var i = 0; i < listInsertCustomers.Count; i++)
        {
            context.Customers.Add(listInsertCustomers[i]);
            context.SaveChanges();
        }
        ResetCache();
        
        Random rand = new Random(new Guid().GetHashCode());
        
        
    }
    [IterationCleanup]
    public void CleanUp()
    {
        CleanCustomers();
    }

    [Benchmark]
    public void UpdateData()
    {
        context.AttachRange(listInsertCustomers);
        
        for (int i = 0; i < listInsertCustomers.Count; i++)
        {
            Customer temp = listInsertCustomers[i];
            temp.Email = "aaaaaaaaa";
            temp.Customerlikescolorgreen = !temp.Customerlikescolorgreen;
            temp.Lastname = "aaaaaaaaa";

            context.Update(temp);
            context.SaveChanges();
        }
    }
}
