using System;
using System.Collections.Generic;

namespace ORM0Entities.autogenerated
{
    public partial class Article
    {
        public Article()
        {
            FkBills = new List<Bill>();
        }
        public int Articlesid { get; set; }
        public string Articlename { get; set; } = null!;
        public decimal Articleprice { get; set; }
        public bool? Ishidden { get; set; }
        public virtual IList<Bill> FkBills { get; set; }
    }
}
