using System;
using System.Collections.Generic;

namespace ORM0Entities.autogenerated
{
    public partial class Customer
    {
        public int Customerid { get; set; }
        public string Lastname { get; set; } = null!;
        public string Email { get; set; } = null!;
        public bool Isvip { get; set; }
        public bool? Customerlikescolorgreen { get; set; }
        public bool? Customerlikescars { get; set; }
        public int Totalarticlesaddedtoshoppingcart { get; set; }
        public decimal Defaultpurchasepricemultiplicator { get; set; }
    }
}
