namespace ORM0Entities.autogenerated
{
    public partial class Knight
    {
        public int Id { get; set; }
        public string? Name { get; set; }
        public int? FkWeaponid { get; set; }
        public virtual Weapon? FkWeapon { get; set; }
    }
}
